### ISSUE TITLE
Error: module not found

### ISSUE THREAD

**Issue by yasenh** [wowchemy/starter-academic#117]
Thanks for sharing your amazing work!
I used to work on v4.8.0 but I recently plan to try the newer version for some other projects. 

So I folked this repo, then setup hugo and go locally and run `hugo server`. 

I saw following issue:

Error: module "github.com/wowchemy/wowchemy-hugo-modules/wowchemy" not found; either add it as a Hugo Module or store it in "xxxx/themes".: module does not exist

I use git submodules on my previous work and this is the first time that I use hugo modules, any suggestions?

**Comment by gcushen** [comment]
The guide to convert your site to use Hugo Modules is here: https://wowchemy.com/docs/install-locally/#convert-an-old-academic-kickstarter-site

Also, refer to the new Update guide at https://wowchemy.com/docs/update/

If you need help, post a the issue with a link to your repo in https://discord.gg/z8wNYzb or https://spectrum.chat/academic

**Comment by yasenh** [comment]
Updates:
I remove hugo from snap installation and download it from https://github.com/gohugoio/hugo/releases, then everything works fine. The Go is still installed from snap.
