### ISSUE TITLE
Need help! Cannot view it or build it locally although I have install prerequisites correctly！

### ISSUE THREAD

**Issue by FanyangMengDev** [wowchemy/starter-academic#119]
Hi there!

Thanks for opening source this perfect theme first.

I made a site myself and after I update to the latest version. I found that the site cannot be built anymore.

No matter the demo file or my own site, they all displays `Error: module "github.com/wowchemy/wowchemy-hugo-modules/wowchemy" not found; either add it as a Hugo Module or store it in "xxxx/themes".: module does not exist` and so many other errors. 

I don't know whether it is because this url is unavaliable?
 https://github.com/wowchemy/wowchemy-hugo-modules/wowchemy 

But currently, your demo site files which is starter-academic cannot be built on my computer to with `hugo server`

The demo site displays an error as following:
```
Error: Error building site: "C:\Users\FanyangMeng\Desktop\academic-master\content\home\demo.md:69:1": failed to extract shortcode: template for shortcode "alert" not found
```
After I deleted the alert shortcode in demo.md and publication.md, 

It displays that 
```
Building sites … WARN 2020/09/12 20:52:33 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/09/12 20:52:33 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/09/12 20:52:33 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/09/12 20:52:33 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/09/12 20:52:33 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/09/12 20:52:33 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/09/12 20:52:33 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/09/12 20:52:33 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/09/12 20:52:33 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/09/12 20:52:33 found no layout file for "JSON" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/09/12 20:52:33 found no layout file for "webappmanifest" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

I can assure you that I have already do what you said in this https://github.com/wowchemy/starter-academic/issues/117#issuecomment-688516652 issue.

Really drives me crazy.

But all things can be built yesterday, and I did not do anything.

Would you please give me a hand? I will appreciate that so much if it possible.

**Comment by FanyangMengDev** [comment]
Cannot locate the reason why this happened and have already reinstalled WIN10.

Issue closed.

**Comment by MFYDev** [comment]
Just wanna give everyone who met this problem one solution.

This problem happens because the system cache of Windows does not fit Hugo anymore.

The most simple way to solve this problem is that when you view it or build it locally, set the --cacheDir to a cache folder in the root dictionary of your site. And Hugo will store the cache in it. Then problem solved.

Hoping you can solve it. : )

**Comment by dgmdevelopment** [comment]
Experiencing similar error but I am working with remote docker containers off of WSL, Win10, VS Code as my IDE.  I have my container running hugo extended and just experimenting as I become more familiar with Hugo.  I run ```hugo new site myproject``` and it does as expected, creating all the files.  In the themes folder then, I thought I could git clone https://github.com/wowchemy/starter-academic.git then just run 

```hugo server -t starter-academic```

but this is giving me an error....

```
Start building sites … 
Built in 6 ms
Error: Error building site: "/workspaces/hugodev/myproject/themes/starter-academic/content/home/demo.md:76:1": failed to extract shortcode: template for shortcode "callout" not found
```
So I'm obviously missing something here.  Thanks for any help.
