### ISSUE TITLE
does update_academic.sh still work?

### ISSUE THREAD

**Issue by matteodefelice** [wowchemy/starter-academic#122]
I have just installed this version of academic and then I have realised that perhaps the file `update_academic.sh` is not valid anymore. On my MacOS it doesn't work because it looks for the folder `themes` which doesn't exist any more.

**Comment by gcushen** [comment]
It has been replaced by https://github.com/wowchemy/starter-academic/blob/master/update_wowchemy.sh . The old file is scheduled to be removed.

The command can be as simple as this now: https://wowchemy.com/docs/update/#update . The script mainly just wraps the Hugo module update command to update Netlify's Hugo version to be compatible if the user is deploying with Netlify.
