### ISSUE TITLE
problem with Alert?

### ISSUE THREAD

**Issue by jrwalker-projects** [wowchemy/starter-academic#124]
in a new empty directory on Windows 10 with RStudio 1.3.1056 and R blogdown package 0.20 (without modifying between new site and the build..):

> blogdown::new_site(theme = "wowchemy/starter-academic")
Congratulations! Your new Hugo site is created in C:\Users\thewa\Documents\Projects\myegregiouswebsite.

Just a few more steps and you're ready to go:

1. Download a theme into the same-named folder.
   Choose a theme from https://themes.gohugo.io/ or
   create your own with the "hugo new theme <THEMENAME>" command.
2. Perhaps you want to add some content. You can add single files
   with "hugo new <SECTIONNAME>\<FILENAME>.<FORMAT>".
3. Start the built-in live server via "hugo server".

Visit https://gohugo.io/ for quickstart guide and full documentation.
trying URL 'https://github.com/wowchemy/starter-academic/archive/master.tar.gz'
Content length 133 bytes
downloaded 4.8 MB

hugo: collected modules in 1523 ms
Error: "C:\Users\thewa\Documents\Projects\myegregiouswebsite\content\home\demo.md:39:1": failed to extract shortcode: template for shortcode "alert" not found
hugo: collected modules in 897 ms
Error: "C:\Users\thewa\Documents\Projects\myegregiouswebsite\content\home\demo.md:39:1": failed to extract shortcode: template for shortcode "alert" not found
hugo: collected modules in 965 ms
Error: "C:\Users\thewa\Documents\Projects\myegregiouswebsite\content\home\demo.md:39:1": failed to extract shortcode: template for shortcode "alert" not found
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:\Users\thewa\AppData\Roaming\Hugo\hugo.exe" convert toYAML --unsafe' execution failed with error code 65535

**Comment by gcushen** [comment]
The official installation guide is at https://wowchemy.com/docs/install/

If you think you have found a bug with Blogdown, report it in the Blogdown GitHub repo.
