### ISSUE TITLE
Unable to edit Homepage

### ISSUE THREAD

**Issue by r4work** [wowchemy/starter-academic#125]
Hi! I am trying to customize my website [https://muditkumarsingh.netlify.app/] following [https://wowchemy.com/docs/page-builder/] and was able to make some changes but I am unable to introduce myself on my home page. I have edited the content/authors/admin/_index.md but the default biography and user details are not getting replaced!!

I am editing the files on my GitHub repository [https://github.com/r4work/starter-academic/tree/master/config].
Looking for expert advice.

**Comment by gcushen** [comment]
This is not a bug. Please ask support questions in the support channel. Netlify will only deploy sites which are error-free. You also appear to have posted the same message in multiple places - see https://github.com/wowchemy/wowchemy-hugo-modules/discussions/1869

**Comment by r4work** [comment]
Hi!
Sorry for duplicate posts.

The thing is- I first posted the question to your earlier repository and
then realised I am working with starter academic repository. So, I
transferred the question to the academic repository.

I am facing the issue again with my new website so have also unmarked the
answer.  Looking forward to your help.
