### ISSUE TITLE
"project" option in the publication widget

### ISSUE THREAD

**Issue by xarthurx** [wowchemy/starter-academic#133]
Hi, the help comment for adding associated project for publications are given as:

```
# Projects (optional).
#   Associate this publication with one or more of your projects.
#   Simply enter your project's filename without extension.
#   E.g. `projects = ["deep-learning"]` references `content/project/deep-learning.md`.
#   Otherwise, set `projects = []`.
projects = [""]
```

However, what I have in the `content/project/` folder is a series of folders each has the structure:
-folderA
 -featured.jpg
 -index.md
-folderB
 -featured.jpg
 -index.md

Adding just the folder name, such as `folderA` to the `project` option doesn't work and will result in errors:
```
: failed to unmarshal YAML: yaml: line 37: could not find expected ':'
```

Any idea?

**Comment by xarthurx** [comment]
The exampleSite provided in the starterkit doesn't contain a example for this case.

**Comment by gcushen** [comment]
We use GitHub issues for managing the project and have a dedicated forum and Discord community for questions: https://github.com/wowchemy/wowchemy-hugo-modules/discussions . Please use this dedicated channel for questions.

Projects are joined on the unique ID of the folder name when using page bundles. However, the error you posted is regarding invalid YAML front matter - see https://wowchemy.com/docs/faq/#error-failed-to-unmarshal-yaml
