### ISSUE TITLE
Failed to download modules when building

### ISSUE THREAD

**Issue by picardch** [wowchemy/starter-academic#134]
Hello,

I built my site successfully on Thursday, but I got this error this morning:

go: github.com/wowchemy/wowchemy-hugo-modules/netlify-cms-academic@v0.0.0-20201001144923-e58ee0ffc576: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /var/folders/g3/z30d793j5bv9mvq4pgwvp1lr0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/cache/vcs/03eb10a0f5c758e6f57cba4cdf4b81a47570b50b3518aecff1c475ee0039297d: exit status 128:
	fatal: not a git repository (or any of the parent directories): .git
hugo: collected modules in 1286 ms
Error: failed to download modules: go command failed: go: github.com/wowchemy/wowchemy-hugo-modules/netlify-cms-academic@v0.0.0-20201001144923-e58ee0ffc576: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /var/folders/g3/z30d793j5bv9mvq4pgwvp1lr0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/cache/vcs/03eb10a0f5c758e6f57cba4cdf4b81a47570b50b3518aecff1c475ee0039297d: exit status 128:
	fatal: not a git repository (or any of the parent directories): .git

I tried checking out a new website and got he same problem with starter-academic.

It works fine with starter-blog and starter book.

Thank you for the great work !!

**Comment by gcushen** [comment]
For the module error, consider the solution to clean the Hugo Module cache at https://wowchemy.com/docs/faq/#error-file-not-found-or-failed-to-extract :

```
hugo mod clean
hugo server
```

If you still experience the same error after that, try updating the modules to the latest versions:

```
hugo mod clean
hugo mod get github.com/wowchemy/wowchemy-hugo-modules/wowchemy@master
hugo mod get github.com/wowchemy/wowchemy-hugo-modules/netlify-cms-academic@master
hugo server
```

Please let us know if the first or second solution above helps to resolve the issue?

Note that we use GitHub issues for managing the project and have a dedicated forum and Discord community for questions: https://github.com/wowchemy/wowchemy-hugo-modules/discussions . Please post future questions there.

**Comment by picardch** [comment]
Thank for your answer.  None of the above solutions worked.

The trick was to cleanup the /var folder manually to removed the cached version.

**Comment by gcushen** [comment]
@picardch Thanks for confirming the solution. Please consider reporting the apparent bug in `hugo mod clean` to the Hugo team: https://github.com/gohugoio/hugo/issues/new/choose
