### ISSUE TITLE
How to make top menu bar items right-justified

### ISSUE THREAD

**Issue by andrewvanleuven** [wowchemy/starter-academic#135]
Not sure if this makes sense, but the previous version of Hugo Academic included a top menu bar where the site name was left-justified and the links were right-justified. The latest version has them all squished together (see my [website](https://andrewvanleuven.com)).

Is there a way to change back to the older way?

Thanks in advance.

**Comment by gcushen** [comment]
We use GitHub issues for managing the project and have a dedicated forum and Discord community for questions: https://github.com/wowchemy/wowchemy-hugo-modules/discussions

In recent versions, there is an alignment option for main menu links in `params.toml`:

```
# Main menu alignment (l = left, c = center, r = right)
main_menu = {align = "c"}
```
