### ISSUE TITLE
BUG: commit 68489423fcfab42bcf1c872883c90fd18a135b50 breaks R blogdown

### ISSUE THREAD

**Issue by Daveyr** [wowchemy/starter-academic#136]
I recently experienced an error building my website using `blogdown` for R and traced it to the following commit

commit 68489423fcfab42bcf1c872883c90fd18a135b50
Author: George Cushen <gcushen@users.noreply.github.com>
Date:   Thu Oct 1 17:43:54 2020 +0100

    refactor: Netlify CMS as an optional module

    ALso
    - update Netlify.toml Hugo version to latest
    - update to latest Wowchemy v5-dev master & upgrade config/ and author profile

When I reverted to a prior commit blogdown now works. Please can you take a look? Along with many others using R to write our websites, I cannot update until this is fixed.

**Comment by gcushen** [comment]
Please report any Blogdown bugs with Hugo Modules in the Blogdown repo: https://github.com/rstudio/blogdown
