### ISSUE TITLE
Make contact_links display multiple columns?

### ISSUE THREAD

**Issue by stephenleo** [wowchemy/starter-academic#139]
Is there a way to make the contact_links display in the contact widget display across multiple columns (side by side) instead of one below the other?

I thought I can build a custom widget by modifying the existing contact widget for it but the link from the documentation seems to be broken: https://github.com/wowchemy/wowchemy-hugo-modules/tree/master/layouts/partials/widgets

Btw, thanks for the awesome work!

**Comment by gcushen** [comment]
You can find the source for the widgets here: https://github.com/wowchemy/wowchemy-hugo-modules/tree/master/wowchemy/layouts/partials/widgets

Copy one to your site and rename it to create your own custom widget: https://wowchemy.com/docs/customization/#override-a-template

Any questions, please join the community on Discord or our GitHub Discussions forum (https://wowchemy.com/ ).
