### ISSUE TITLE
Hugo academic blogdown build fails after adding a publication content item: execute of template failed (…) error calling index: index of untyped nil

### ISSUE THREAD

**Issue by martakarass** [wowchemy/starter-academic#147]
I am building from scratch the Hugo-powered (version v0.78.2) website with `wowchemy/starter-academic` (today's most recent is [ea20142](https://github.com/wowchemy/starter-academic/commit/ea201422d2e4e2480ad2448581ed3ff09e001d10)) theme with the use of `R` `blogdown` (version 0.21). I put it up by running `blogdown::new_site(theme = "wowchemy/starter-academic")`. I have successfully edited number of `content` dirs, including `content/post` and `content/talk`. I then started working at `content/publication`: 

- I removed all but `content/publication/_index.md`
- I typed `blogdown::new_content(path = 'publication/foo.md', kind = 'publication')`

After executing the command above, the page no longer renders, with the following error: 

    Rebuild failed:
    
    Failed to render pages: render of "page" failed: "/Users/marta/Dropbox/my_personal_website/themes/github.com/wowchemy/wowchemy-hugo-modules/wowchemy/layouts/publication/single.html:14:47": execute of template failed: template: publication/single.html:14:47: executing "main" at <index .Params.publication_types 0>: error calling index: index of untyped nil
    12
    13
    14
    15
    16
        {{ end }}
    
        {{ if and (.Params.publication_types) (ne (index .Params.publication_types 0) "0") }}
        <div class="row">
          <div class="col-md-1"></div>
    Hugo Static Site Generator v0.78.2/extended darwin/amd64 BuildDate: unknown.  
  
  
Please kindly help troubleshoot this.

**Comment by gcushen** [comment]
Users have reported that Blogdown does not yet fully support recent Hugo versions. In this case, it sounds as though Blogdown might not be utilising the publication template from https://github.com/wowchemy/wowchemy-hugo-modules/blob/master/wowchemy/archetypes/publication/index.md .

If you stop Hugo, add the front matter from the template and re-run Hugo, it might workaround the issue.

**Comment by martakarass** [comment]
Hi @gcushen I think this helped! After that I also saw some error complaining about `/content/home/gallery/index.md`, and I just trashed the whole ``/content/home/gallery` folder I have no need for, and it renders correctly (mentioning as I have not seen this error before working with `content/publication`, despite it seems not related to me 😳 ) Thanks a lot for your work!

**Comment by gcushen** [comment]
Glad to hear it's working!

After modifying files (especially in `/content/home/` folder) whilst Hugo Server is running, Hugo Server often requires restarting, which may explain why you saw unrelated errors.
