### ISSUE TITLE
Website not updating new changes.

### ISSUE THREAD

**Issue by seanswyi** [wowchemy/starter-academic#148]
Hi. I recently started using your product. I haven't had any problem until now, but I noticed from one point that the website stopped applying changes made to the GitHub repo.

I've tried updating the `experience` section and also the title for the website. I added a `layouts/partials/head_custom.html` in an attempt to make some changes but they haven't been updated.

My website repo is [here](https://github.com/seanswyi/sean-website). I'd appreciate any tips on what might be the problem. Thanks.

**Comment by gcushen** [comment]
See https://wowchemy.com/docs/faq/#changes-do-not-show-on-my-site
