### ISSUE TITLE
Rmarkdown cannot present image

### ISSUE THREAD

**Issue by anhhd** [wowchemy/starter-academic#150]
**Observation:** RMD post cannot present image rendered with R code

**Steps to reproduce**:

- Create a new post
- Add r-code in the RMD file:

```r
plot(cars)
```

- Save it
- Build site - error shown as below

![error blogdown](https://user-images.githubusercontent.com/17422533/99904634-ac5ca480-2cfe-11eb-874c-eea9b0531e7e.png)

I used other theme, such as `hugo-lithium` but only `starter-academic` faces this issue.

**System environment**:

- Windows 10
- R 3.60
- Blogdown 0.21
- Hugo 0.78.2

**Comment by gcushen** [comment]
Wowchemy should not alter image URLs, in your case, image HTML is generated by Blogdown and Hugo.

If you wish to make an improvement, you are welcome to open a PR.

The Blogdown repo is located at https://github.com/rstudio/blogdown

Also, see https://wowchemy.com/docs/front-matter/ :

> Hugo is used as the HTML generator so RMarkdown should be saved with the .Rmarkdown file extension rather than as HTML with the .Rmd extension.
