### ISSUE TITLE
Post links directing to empty pages.

### ISSUE THREAD

**Issue by seanswyi** [wowchemy/starter-academic#167]
I'm creating blog posts like it says [here](https://wowchemy.com/docs/managing-content/#create-a-blog-post) but when I click the post it directs me to an empty page.

If I do `hugo new --kind post posts/testing` then inside the `testing` directory I have an `index.md` where I can put in the info. Writing something in the `summary` section will display the summary, but when I click on the title of the post it takes me to an empty page. I've tried adding a `testing.md` file inside and outside the directory but I still can't manage to get it to work.

It would help a lot if you could give me some tips or direct me to where to look. Thanks.

**Comment by gcushen** [comment]
Please follow the Questions link in the Readme: https://github.com/wowchemy/wowchemy-hugo-modules/discussions
